### ISSUE TITLE
Any license specification in mind? What are the terms of reuse of your custom desert and snow scenes?

### ISSUE THREAD

**Issue by timeamagyar** [markste-in/ai_airplanes#1]
Hello Tommy,

I have done the same course on Udemy a few weeks back. I am about to extend it, especially the ML part. I have seen that you created your own versions of the desert and snow scenes, placing the rocks differently and using a slightly altered race path. I would love to reuse your custom scenes, so I can have a separate scene for training and inferencing. 
I am doing all of this for a university project, and need to make sure that I have your explicit consent, to avoid plagiarism, among others.
For this, it would be really beneficial to have your explicit okay, as unfortunately, you have not defined any license for your project.

Your feedback would be highly appreciated! 

Kind regards,

Timea

**Comment by markste-in** [comment]
Hey!

Sure! Feel free to do whatever u like with it!
It’s fine with me!

Tommy

**Comment by timeamagyar** [comment]
Awesome! Thanks!
